package GUI;

import java.awt.EventQueue;

/**
 *
 * @author Va¹ek & Vítek
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI2
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createAccountBut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        deleteAccountBut = new javax.swing.JButton();
        updateAccountBut = new javax.swing.JButton();
        showAccountsBut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        executePaymentBut = new javax.swing.JButton();
        deletePaymentBut = new javax.swing.JButton();
        updatePaymentBut = new javax.swing.JButton();
        showPaymentsBut = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banking system application");

        createAccountBut.setText("Create account");
        createAccountBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountButActionPerformed(evt);
            }
        });

        jLabel1.setText("Account actions");

        deleteAccountBut.setText("Delete account");
        deleteAccountBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAccountButActionPerformed(evt);
            }
        });

        updateAccountBut.setText("Update account");
        updateAccountBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAccountButActionPerformed(evt);
            }
        });

        showAccountsBut.setText("Show all accounts");
        showAccountsBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAccountsButActionPerformed(evt);
            }
        });

        jLabel2.setText("Payment actions");

        executePaymentBut.setText("Execute payment");
        executePaymentBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executePaymentButActionPerformed(evt);
            }
        });

        deletePaymentBut.setText("Delete payment");
        deletePaymentBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePaymentButActionPerformed(evt);
            }
        });

        updatePaymentBut.setText("Update payment");
        updatePaymentBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePaymentButActionPerformed(evt);
            }
        });

        showPaymentsBut.setText("Show all payments");
        showPaymentsBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPaymentsButActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(aboutMenuItem);
        jMenu1.add(jSeparator1);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1)
                        .addGap(94, 94, 94)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(updateAccountBut, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(showAccountsBut, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(deleteAccountBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(createAccountBut, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(executePaymentBut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updatePaymentBut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deletePaymentBut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(showPaymentsBut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createAccountBut)
                    .addComponent(executePaymentBut))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteAccountBut)
                    .addComponent(deletePaymentBut))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateAccountBut)
                    .addComponent(updatePaymentBut))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showAccountsBut)
                    .addComponent(showPaymentsBut))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteAccountButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAccountButActionPerformed
        
     EventQueue.invokeLater( ()-> { 
        DeleteAccount win = new DeleteAccount();
        win.setVisible(true);
     });
     
    }//GEN-LAST:event_deleteAccountButActionPerformed

    private void updateAccountButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAccountButActionPerformed
     
     EventQueue.invokeLater( ()-> { 
        UpdateAccount win = new UpdateAccount();
        win.setVisible(true);
     });
     
    }//GEN-LAST:event_updateAccountButActionPerformed

    private void executePaymentButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executePaymentButActionPerformed
      EventQueue.invokeLater( ()-> { 
        ExecutePayment win = new ExecutePayment();
        win.setVisible(true);
     });
    }//GEN-LAST:event_executePaymentButActionPerformed

    private void createAccountButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountButActionPerformed
        
     EventQueue.invokeLater( ()-> { 
        CreateAccount win = new CreateAccount();
        win.setVisible(true);
     });

    }//GEN-LAST:event_createAccountButActionPerformed

    private void updatePaymentButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePaymentButActionPerformed
     EventQueue.invokeLater( ()-> { 
        UpdatePayment win = new UpdatePayment();
        win.setVisible(true);
     });
    }//GEN-LAST:event_updatePaymentButActionPerformed

    private void showAccountsButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAccountsButActionPerformed
     EventQueue.invokeLater( ()-> { 
        AllAccounts win = new AllAccounts();
        win.setVisible(true);
     });
    }//GEN-LAST:event_showAccountsButActionPerformed
//
    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
  
    }//GEN-LAST:event_jMenu1ActionPerformed
//
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void deletePaymentButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePaymentButActionPerformed
     EventQueue.invokeLater( ()-> { 
        DeletePayment win = new DeletePayment();
        win.setVisible(true);
     });
    }//GEN-LAST:event_deletePaymentButActionPerformed

    private void showPaymentsButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPaymentsButActionPerformed
     EventQueue.invokeLater( ()-> { 
        AllPayments win = new AllPayments();
        win.setVisible(true);
     });
    }//GEN-LAST:event_showPaymentsButActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
     EventQueue.invokeLater( ()-> { 
        About win = new About();
        win.setVisible(true);
     });
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton createAccountBut;
    private javax.swing.JButton deleteAccountBut;
    private javax.swing.JButton deletePaymentBut;
    private javax.swing.JButton executePaymentBut;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JButton showAccountsBut;
    private javax.swing.JButton showPaymentsBut;
    private javax.swing.JButton updateAccountBut;
    private javax.swing.JButton updatePaymentBut;
    // End of variables declaration//GEN-END:variables
}
